{dede:pagestyle maxwidth='800' pagepicnum='9999' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/130608/1-13060R01110.jpg' text='' width='700' height='467'} /uploads/allimg/130608/1-13060R01110.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130608/1-13060R01112.jpg' text='' width='700' height='467'} /uploads/allimg/130608/1-13060R01112.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130608/1-13060R01113.jpg' text='' width='700' height='467'} /uploads/allimg/130608/1-13060R01113.jpg {/dede:img}
