<li style="float:left;margin-left:6px;margin-right:6px">
      <div class='nppts' onmouseover="this.className='nppts2'"  onmouseout="this.className='nppts'"> <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]"  alt="[field:title/]" title="[field:title/]"  class="imgss" /></a>
        <div class="btss">
          <div style="color:#ffffff;font-size:10px;height:11px;line-height:11px">Date: </b>[field:pubdate function='strftime("%Y/%m/%d",@me)'/]</div>
          <div style="margin-top:5px"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
        </div>
        <div class="lss">[field:title/]</div>
      </div>
    </li>