<?php
$z[0]=Array("pubdate","",190,236);
$z[0][4]['function']="strftime(\"%d\",@me)";
$z[1]=Array("pubdate","",303,349);
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("pubdate","",399,451);
$z[2][4]['function']="strftime(\"%Y/%m/%d\",@me)";
$z[3]=Array("arcurl","",633,648);
$z[4]=Array("title","",667,681);
$z[5]=Array("arcurl","",706,721);
$z[6]=Array("global","",749,782);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("description","",876,896);

?>