<div style="width:966px;height:170px">

			<div style="width:260px;float:left">
				   <div>
				        <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width=238 height=147 style="padding:8px;background:#F7F7EF"></a>
				   </div>
				</div>
				<div style="width:696px;float:right">
				    <div style="border-bottom:1px dashed #cccccc;height:40px;line-height:40px;font-size:22px;font-family:微软雅黑"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
				    <div style="margin-top:10px;color:#888888;height:90px">[field:description/]</div>
				    <div><a href="[field:arcurl/]" target="_blank"><img src="[field:global.cfg_templets_skin/]/images/xx.jpg"></a></div>
				</div>
			</div>
			<div style="text-align:center"><img src="[field:global.cfg_templets_skin/]/images/xw.jpg"></div>