<li style="float:left;margin-left:6px;margin-right:6px">
      <div class='nppxrfx' onmouseover="this.className='nppxrfx2'"  onmouseout="this.className='nppxrfx'"> <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]"  alt="[field:title/]" title="[field:title/]"  class="imgss" /></a>
        <div class="btss"> <a href="[field:arcurl/]" target="_blank">[field:title/]</a><br>
          <span style="color:#666666"><b>POST TIME : </b>[field:pubdate function='strftime("%Y/%m/%d",@me)'/]</span> </div>
      </div>
    </li>