<?php
$z[0]=Array("pagestyle","",0,93);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="9999";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/130531/1-130531153133.jpg ",95,242);
$z[1][4]['ddimg']="/uploads/allimg/130531/1-130531153133.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="533";

?>