<li style="float:left;width:308px;height:220px;margin-left:5px;margin-right:5px;margin-bottom:30px">
					<div class='nppjd' onmouseover="this.className='nppjd2'"  onmouseout="this.className='nppjd'">
	                        <div style="padding:10px 10px 0px 10px">
	                           <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width=298px height=185px ></a>
	                        </div>
	                        <div style="padding-left:10px;font-size:12px"  class="viv">VISITORS：[field:click/]&nbsp;&nbsp;&nbsp; DATE：[field:pubdate function='strftime("%Y/%m/%d",@me)'/]</div>
					        <div style="padding-left:10px;" class="tit">Title：<b>[field:title/]</b></div>
					</div>
				</li>