<li style="float:left;margin-left:5px;margin-right:5px">
      <div class='nppiijd' onmouseover="this.className='nppiijd2'"  onmouseout="this.className='nppiijd'"> <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]"  alt="[field:title/]" title="[field:title/]"  style="width:298px;height:185px;padding:5px;border:1px solid #efefef" /></a>
        <div class="btss"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
      </div>
      <div style="color:#888888"><b>POST TIME : </b>[field:pubdate function='strftime("%Y/%m/%d",@me)'/]</div>
    </li>