<?php
$z[0]=Array("pagestyle","",0,93);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="9999";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/130608/1-13060R00J6.jpg ",95,238);
$z[1][4]['ddimg']="/uploads/allimg/130608/1-13060R00J6.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="700";
$z[1][4]['height']="467";
$z[2]=Array("img"," /uploads/allimg/130608/1-13060R00J8.jpg ",240,383);
$z[2][4]['ddimg']="/uploads/allimg/130608/1-13060R00J8.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="700";
$z[2][4]['height']="467";
$z[3]=Array("img"," /uploads/allimg/130608/1-13060R00J9.jpg ",385,528);
$z[3][4]['ddimg']="/uploads/allimg/130608/1-13060R00J9.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="700";
$z[3][4]['height']="467";
$z[4]=Array("img"," /uploads/allimg/130608/1-13060R00K0.jpg ",530,673);
$z[4][4]['ddimg']="/uploads/allimg/130608/1-13060R00K0.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="700";
$z[4][4]['height']="467";

?>