{dede:pagestyle maxwidth='800' pagepicnum='9999' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/130608/1-13060R00J6.jpg' text='' width='700' height='467'} /uploads/allimg/130608/1-13060R00J6.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130608/1-13060R00J8.jpg' text='' width='700' height='467'} /uploads/allimg/130608/1-13060R00J8.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130608/1-13060R00J9.jpg' text='' width='700' height='467'} /uploads/allimg/130608/1-13060R00J9.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130608/1-13060R00K0.jpg' text='' width='700' height='467'} /uploads/allimg/130608/1-13060R00K0.jpg {/dede:img}
