<?php
$z[0]=Array("field","",243,262);
$z[0][4]['name']="title";
$z[1]=Array("global","",263,289);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",310,342);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",429,459);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",495,522);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",541,576);
$z[5][4]['filename']="top.html";
$z[6]=Array("arclist","\n<div  class=\"sban\" style=\"height:393px;background:url([field:litpic/]) center\"></div>\n",578,721);
$z[6][4]['idlist']="1";
$z[6][4]['channelid']="1";
$z[7]=Array("include","",723,759);
$z[7][4]['filename']="dhcc.html";
$z[8]=Array("global","",799,831);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1021,1053);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("field","",1144,1166);
$z[10][4]['name']="typename";
$z[11]=Array("channel","\n										<div class=\"ts2\" ><a href=\"[field:typeurl/]\">[field:typename/]</a></div>\n								   ",1291,1498);
$z[11][4]['orderway']="desc";
$z[11][4]['currentstyle']="<div class='ts1'><a href='#' >~typename~</a></div>";
$z[12]=Array("field","",1578,1599);
$z[12][4]['name']="content";
$z[13]=Array("include","",1610,1645);
$z[13][4]['filename']="end.html";

?>