<div class='nppjiage' onmouseover="this.className='nppjiage2'"  onmouseout="this.className='nppjiage'">
						 <div style="float:left;width:260px;text-align:center;height:168px">
						 
<a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width=238 height=147 class="imss"></a>

						 </div>
						 <div style="float:right;width:700px;height:168px">
						 			<div style="height:38px;line-height:38px;font-size:27px;font-family:微软雅黑;border-bottom:1px dashed #cccccc"><a href="[field:arcurl/]" target="_blank">[field:title/]</a>&nbsp;&nbsp;<a href="[field:arcurl/]" target="_blank"><span style="font-size:16px">（点击了解详情）</span></a></div>
								    <div style="font-size:14px;height:36px;line-height:36px;margin-top:5px">RMB：<span class="jiages">[field:jiage/]</span>元</div>
								    <div style="margin-top:5px;height:56px" class="miaoshu">[field:description/]</div>
								    <div class="reads"><a href="[field:arcurl/]" target="_blank">>>READ MORE</a></div>
						 </div>

				</div>	
			<div ><img src="[field:global.cfg_templets_skin/]/images/xs.jpg"></div>