<?php
$z[0]=Array("pagestyle","",0,93);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="9999";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/130531/1-130531154359.jpg ",95,242);
$z[1][4]['ddimg']="/uploads/allimg/130531/1-130531154359.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="533";
$z[2]=Array("img"," /uploads/allimg/130531/1-130531154401.jpg ",244,391);
$z[2][4]['ddimg']="/uploads/allimg/130531/1-130531154401.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="533";
$z[3]=Array("img"," /uploads/allimg/130531/1-130531154406.jpg ",393,540);
$z[3][4]['ddimg']="/uploads/allimg/130531/1-130531154406.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="800";
$z[3][4]['height']="533";

?>