<?php
$z[0]=Array("arclist","\r\n		    <img src=\"[field:litpic/]\" >\r\n	    ",56,156);
$z[0][4]['idlist']="73";
$z[0][4]['channelid']="1";
$z[1]=Array("global","",239,266);
$z[1][4]['name']="zixun";
$z[2]=Array("global","",367,394);
$z[2][4]['name']="qqone";
$z[3]=Array("global","",489,521);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",650,682);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",736,765);
$z[5][4]['name']="address";

?>