<div class='npp' onmouseover="this.className='npp2'"  onmouseout="this.className='npp'">
						 <div style="float:left;width:99px;text-align:center;height:96px">
						   <span class="yues">[field:pubdate function='strftime("%d",@me)'/]</span><br>
						   <span style="font-size:20px;font-weight:400;">[field:pubdate function='strftime("%b",@me)'/]</span><br>
						   <span style="color:#888888" >[field:pubdate function='strftime("%Y/%m/%d",@me)'/]</span>

						 </div>
						 <div style="float:right;width:860px;height:96px">
						 			<div style="height:30px;line-height:30px;font-size:20px;font-family:微软雅黑;"><a href="[field:arcurl/]" >[field:title/]</a>&nbsp;&nbsp;<a href="[field:arcurl/]" ><img src="[field:global.cfg_templets_skin/]/images/jr.gif"></a></div>
								    <div style="margin-top:10px;color:#888888;height:90px">[field:description/]</div>
						 </div>

				</div>