<?php
$z[0]=Array("field","",243,262);
$z[0][4]['name']="title";
$z[1]=Array("global","",263,289);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",310,342);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",429,459);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",495,522);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",541,576);
$z[5][4]['filename']="top.html";
$z[6]=Array("arclist","\n<div  class=\"sban\" style=\"height:393px;background:url([field:litpic/]) center\"></div>\n",578,722);
$z[6][4]['idlist']="26";
$z[6][4]['channelid']="1";
$z[7]=Array("include","",725,761);
$z[7][4]['filename']="dhcc.html";
$z[8]=Array("global","",801,833);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1021,1053);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("field","",1144,1166);
$z[10][4]['name']="typename";
$z[11]=Array("channel","\n										<div class=\"ts2\" ><a href=\"[field:typeurl/]\">[field:typename/]</a></div>\n								   ",1291,1498);
$z[11][4]['orderway']="desc";
$z[11][4]['currentstyle']="<div class='ts1'><a href='#' >~typename~</a></div>";
$z[12]=Array("list","\n				<div class='npp' onmouseover=\"this.className='npp2'\"  onmouseout=\"this.className='npp'\">\n						 <div style=\"float:left;width:99px;text-align:center;height:96px\">\n						   <span class=\"yues\">[field:pubdate function='strftime(\"%d\",@me)'/]</span><br>\n						   <span style=\"font-size:20px;font-weight:400;\">[field:pubdate function='strftime(\"%b\",@me)'/]</span><br>\n						   <span style=\"color:#888888\" >[field:pubdate function='strftime(\"%Y/%m/%d\",@me)'/]</span>\n\n						 </div>\n						 <div style=\"float:right;width:860px;height:96px\">\n						 			<div style=\"height:30px;line-height:30px;font-size:20px;font-family:微软雅黑;\"><a href=\"[field:arcurl/]\" >[field:title/]</a>&nbsp;&nbsp;<a href=\"[field:arcurl/]\" ><img src=\"[field:global.cfg_templets_skin/]/images/jr.gif\"></a></div>\n								    <div style=\"margin-top:10px;color:#888888;height:90px\">[field:description/]</div>\n						 </div>\n\n				</div>	\n				\n	",1762,2709);
$z[12][4]['pagesize']="10";
$z[13]=Array("pagelist","",2799,2877);
$z[13][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[13][4]['listsize']="5";
$z[14]=Array("include","",2963,2998);
$z[14][4]['filename']="end.html";

?>