<?php
$z[0]=Array("field","",243,262);
$z[0][4]['name']="title";
$z[1]=Array("global","",263,289);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",310,342);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",429,459);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",495,522);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",541,576);
$z[5][4]['filename']="top.html";
$z[6]=Array("arclist","\n<div  class=\"sban\" style=\"height:393px;background:url([field:litpic/]) center\"></div>\n",578,722);
$z[6][4]['idlist']="54";
$z[6][4]['channelid']="1";
$z[7]=Array("include","",725,761);
$z[7][4]['filename']="dhcc.html";
$z[8]=Array("global","",801,833);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1022,1054);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("field","",1160,1182);
$z[10][4]['name']="typename";
$z[11]=Array("channel","\n										<div class=\"ts2\" ><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></div>\n								   ",1307,1538);
$z[11][4]['orderway']="desc";
$z[11][4]['currentstyle']="<div class='ts1'><a href='~typelink~'>~typename~</a></div>";
$z[12]=Array("field","",1753,1773);
$z[12][4]['name']="litpic";
$z[13]=Array("field","",1907,1926);
$z[13][4]['name']="title";
$z[14]=Array("field","",1997,2016);
$z[14][4]['name']="jiage";
$z[15]=Array("field","",2078,2096);
$z[15][4]['name']="body";
$z[16]=Array("include","",2114,2149);
$z[16][4]['filename']="end.html";

?>