<?php
$z[0]=Array("field","",246,265);
$z[0][4]['name']="title";
$z[1]=Array("global","",266,292);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",314,346);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",434,464);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",501,528);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",550,585);
$z[5][4]['filename']="top.html";
$z[6]=Array("arclist","\r\n<div  class=\"sban\" style=\"height:393px;background:url([field:litpic/]) center\"></div>\r\n",589,735);
$z[6][4]['idlist']="41";
$z[6][4]['channelid']="1";
$z[7]=Array("include","",740,776);
$z[7][4]['filename']="dhcc.html";
$z[8]=Array("global","",819,851);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1048,1080);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("field","",1186,1208);
$z[10][4]['name']="typename";
$z[11]=Array("channel","\r\n		<div class=\"ts2vv\" ><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></div>\r\n		",1291,1511);
$z[11][4]['orderway']="desc";
$z[11][4]['currentstyle']="<div class='ts1vv'><a href='~typelink~'>~typename~</a></div>";
$z[12]=Array("list","\r\n				<li style=\"float:left;width:308px;height:220px;margin-left:5px;margin-right:5px;margin-bottom:30px\">\r\n					<div class='nppjd' onmouseover=\"this.className='nppjd2'\"  onmouseout=\"this.className='nppjd'\">\r\n	                        <div style=\"padding:10px 10px 0px 10px\">\r\n	                           <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" width=298px height=185px ></a>\r\n	                        </div>\r\n	                        <div style=\"padding-left:10px;font-size:12px\"  class=\"viv\">VISITORS：[field:click/]&nbsp;&nbsp;&nbsp; DATE：[field:pubdate function='strftime(\"%Y/%m/%d\",@me)'/]</div>\r\n					        <div style=\"padding-left:10px;\" class=\"tit\">Title：<b>[field:title/]</b></div>\r\n					</div>\r\n				</li>	\r\n	",1696,2486);
$z[12][4]['pagesize']="12";
$z[13]=Array("pagelist","",2614,2692);
$z[13][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[13][4]['listsize']="5";
$z[14]=Array("include","",2784,2819);
$z[14][4]['filename']="end.html";

?>