<?php
$z[0]=Array("field","",246,265);
$z[0][4]['name']="title";
$z[1]=Array("global","",266,292);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",314,346);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",434,464);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",501,528);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",550,585);
$z[5][4]['filename']="top.html";
$z[6]=Array("arclist","\r\n<div  class=\"sban\" style=\"height:393px;background:url([field:litpic/]) center\"></div>\r\n",589,735);
$z[6][4]['idlist']="41";
$z[6][4]['channelid']="1";
$z[7]=Array("include","",740,776);
$z[7][4]['filename']="dhcc.html";
$z[8]=Array("global","",819,851);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1048,1080);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("field","",1186,1208);
$z[10][4]['name']="typename";
$z[11]=Array("channel","\r\n		<div class=\"ts2vv\" ><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></div>\r\n		",1291,1511);
$z[11][4]['orderway']="desc";
$z[11][4]['currentstyle']="<div class='ts1vv'><a href='~typelink~'>~typename~</a></div>";
$z[12]=Array("field","",1600,1619);
$z[12][4]['name']="title";
$z[13]=Array("field","",1656,1674);
$z[13][4]['name']="body";
$z[14]=Array("include","",1698,1733);
$z[14][4]['filename']="end.html";

?>